### ISSUE TITLE
BuildFactory

### ISSUE THREAD

**Issue by thaflo** [lorglas/yab#27]
creating a binary version with BuildFactory the executable can't be executed:
line one: syntax error at "="

that's happening on different app builds

**Comment by lorglas** [comment]
Hi thaflo, 

thank you for your report. I take a look. The next version is in work. 

Regards lorglas

**Comment by bbjimmy** [comment]
Change line 434 in BuileFactory.yab to:

 print "DumpProg("+f$+")"

Fixes the BuildFactory for me.


On 11/2/23, lorglas ***@***.***> wrote:
> Hi thaflo,
>
> thank you for your report. I take a look. The next version is in work.
>
> Regards lorglas
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/lorglas/yab/issues/27#issuecomment-1791039673
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
bbjimmy

http://www.coquillemartialarts.com
http://www.fatelk.com
http://yab.orgfree.com

**Comment by thaflo** [comment]
found out that  a code line like
`if (a == 1)`
leads to the error I posted. maybe a check should stop the build process with an appropriate message?
I use now the version from 2020, which works.

**Comment by lorglas** [comment]
Use latest Version
